version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/tutorial-be
hooks:
  BeforeInstall:
    - location: scripts/convertounix.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy_process.sh
      timeout: 3000
      runas: root