version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu
hooks:
  ApplicationStart:
    - location: scripts/deploy_process.sh
      timeout: 3000
      runas: ubuntu