version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/tutorial-be
hooks:
  AfterInstall:
    - location: /home/ubuntu/tutorial-be/scripts/deploy_process.sh
      timeout: 3000
      runas: root