version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/tutorial-be
permissions:
  - object: /
    pattern: "0777"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy_process.sh
      timeout: 3000
      runas: root