version: 0.2
env:
  secrets-manager:
    BeImageName: prod/tutorial-app-be-configs:BackendImageName
    ImageCompressedName: prod/tutorial-app-be-configs:CompressedImageName
phases:
  pre_build:
    commands:
      - echo "Import compressed image..."
      - cat ${ImageCompressedName}.tar | docker import - $BeImageName:latest
  build:
    commands:
      - echo "Building the Docker image for Trivy scan..."
      - echo "Scanning image for vulnerabilities with Trivy..."
      - trivy image --severity HIGH,CRITICAL --db-repository public.ecr.aws/aquasecurity/trivy-db:2 -f json -o results.json $BeImageName:latest
      - echo "Checking Trivy scan results..."
      - cat results.json
      - |
        CRITICAL=$(jq '[.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | select(.Severity == "CRITICAL")] | length' results.json || echo 0)
        HIGH=$(jq '[.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | select(.Severity == "HIGH")] | length' results.json || echo 0)
        if [ "$CRITICAL" -gt 0 ]; then
          echo "FAIL: Found $CRITICAL Critical vulnerabilities. Please address them before proceeding."
        elif [ "$HIGH" -gt 0 ]; then
          echo "WARNING: Found $HIGH High vulnerabilities. Please consider addressing them."
        else
          echo "PASS: No High or Critical vulnerabilities found."
        fi
  post_build:
    commands:
      - echo "Saving Docker image as a .tar file for artifacts..."
      - docker save -o ${ImageCompressedName}.tar $BeImageName:latest
artifacts:
  files:
    - buildspec.push-image.yml
    - ${ImageCompressedName}.tar
