version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t longnt20/tutorial-app-be:latest .
      - docker push longnt20/tutorial-app-be:latest

env:
  secrets-manager:
    DOCKER_HUB_USERNAME: DockerCredentials:username
    DOCKER_HUB_PASSWORD: DockerCredentials:password