version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: lts
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t longnt20/tutorial-app-be:latest .
      - docker push longnt20/tutorial-app-be:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"BackendContainer","imageUri":"longnt20/tutorial-app-be:latest"}]' > imagedefinitions.json
env:
  secrets-manager:
    DOCKER_HUB_USERNAME: DockerCredentials:username
    DOCKER_HUB_PASSWORD: DockerCredentials:password
cache:
  paths:
    - "node_modules/**/*"
    - "$HOME/.sonar/**/*"
artifacts:
  files:
    - imagedefinitions.json